# Generated by Django 3.2.15 on 2022-10-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_user_wishlist'),
        ('profiles', '0002_userprofile_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_wishlist',
            field=models.ManyToManyField(blank=True, related_name='product_wishlist', to='products.Product'),
        ),
    ]
