# Generated by Django 3.2.15 on 2022-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_variety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
