# Generated by Django 3.2.15 on 2022-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_country'),
        ('products', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='profiles.UserProfile'),
        ),
    ]
