# Generated by Django 3.2.15 on 2022-10-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_wishlist',
        ),
    ]
